### ISSUE TITLE
Meteor build attempt failing!

### ISSUE THREAD

**Issue by fvpDev** [onmodulus/modulus-cli#127]
All my code is fine too...
```
Compressing project...
3.6 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.9.6)
Initializing Meteor environment.
Using METEOR@1.3.5.1.
Demeteorizing application...
Build attempt failed, attempting again.
```

**Comment by fvpDev** [comment]
Hmmm..I didn't change anything and it worked the second time around. Strange..

**Comment by fvpDev** [comment]
Tried uploading/deploying via http://my.modulus.io:
```
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
/mnt/input/.meteor directory must exist.
Build attempt failed, attempting again.
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
/mnt/input/.meteor directory must exist.
Build attempt failed, attempting again.
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
/mnt/input/.meteor directory must exist.
Build failed, reverting project.
```

**Comment by fvpDev** [comment]
```
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.9.6)
Initializing Meteor environment.
Using METEOR@1.3.5.1.
Demeteorizing application...
Using METEOR@1.3.5.1.
Demeteorizing application...
Demeteorization complete.
Installing packages from /mnt/output/bundle/programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.13 install /mnt/output/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Demeteorization complete.
Installing packages from /mnt/output/bundle/programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.13 install /mnt/output/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/mnt/output/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/mnt/output/bundle/programs/server/node_modules/fibers/build'
Installed in `/mnt/output/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
meteor-dev-bundle@0.0.0 /mnt/output/bundle/programs/server
├── ansi-styles@1.1.0 
├── escape-string-regexp@1.0.5 
├── fibers@1.0.13 
├─┬ has-ansi@0.1.0 
│ └── ansi-regex@0.2.1 
├── meteor-promise@0.7.2 
├─┬ promise@7.1.1 
│ └── asap@2.0.4 
├── semver@4.1.0 
├─┬ source-map-support@0.3.2 
│ └─┬ source-map@0.1.32 
│   └── amdefine@1.0.0 
├── strip-ansi@0.3.0 
├── supports-color@0.2.0 
├── type-of@2.0.1 
└── underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
Uploading completed build.
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
gyp ERR! System Linux 3.13.0-92-generic
gyp ERR! command "node" "/mnt/output/.modulus/nvm/v0.10.41/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /mnt/output/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v0.10.41
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
sh: 1: nodejs: not found
meteor-dev-bundle@0.0.0 /mnt/output/bundle/programs/server
├── ansi-styles@1.1.0 
├── escape-string-regexp@1.0.5 
├─┬ has-ansi@0.1.0 
│ └── ansi-regex@0.2.1 
├── meteor-promise@0.7.2 
├─┬ promise@7.1.1 
│ └── asap@2.0.4 
├── semver@4.1.0 
├─┬ source-map-support@0.3.2 
│ └─┬ source-map@0.1.32 
│   └── amdefine@1.0.0 
├── strip-ansi@0.3.0 
├── supports-color@0.2.0 
├── type-of@2.0.1 
└── underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "node" "/mnt/output/.modulus/nvm/v0.10.41/bin/npm" "install" "--production" "--quiet"
npm ERR! node v0.10.41
npm ERR! npm  v3.9.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/output/bundle/programs/server/npm-debug.log
npm install failed, trying again

> fibers@1.0.13 install /mnt/output/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/mnt/output/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/mnt/output/bundle/programs/server/node_modules/fibers/build'
Installed in `/mnt/output/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
meteor-dev-bundle@0.0.0 /mnt/output/bundle/programs/server
└── fibers@1.0.13 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
Uploading completed build.
```

**Comment by fvpDev** [comment]
I downloaded the current deployment of my project and tried re-uploading it without changing anything and still get same log output. Is anyone there? My site is in production, it'd be nice to know that someone is seeing this.

**Comment by harlanj** [comment]
@fvpDev Sorry for the problems. At first, it looks like you have builds going over each other. Can you give me a project id?

**Comment by fvpDev** [comment]
projectID# 80631

**Comment by harlanj** [comment]
I'm trying to deploy now...

**Comment by harlanj** [comment]
Logs from my deploy:

```
Deploying Meteor version 1.3.5.1

Compressing project...
3.6 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.9.6)
Initializing Meteor environment.
Using METEOR@1.3.5.1.
Demeteorizing application...
Build attempt failed, attempting again.
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.9.6)
Initializing Meteor environment.
Using METEOR@1.3.5.1.
Demeteorizing application...

[✓] project-80631 running at project80631-83053.onmodulus.net
```

Started at 1:13:25 PM
Ended at 1:29:31 PM

Build attempt failed twice.

**Comment by fvpDev** [comment]
Yup; I've been getting that when using the cli (sry I didn't post the second build fail originally)....what do I need to do to fix it?

**Comment by harlanj** [comment]
I'm trying with the cli at version 5.x.x and switching the runtime to node. I can let you know when it finishes the deploy

**Comment by harlanj** [comment]
How long does it take for the `demeteorize` command to finish for you locally? It's been going on for almost 20 minutes

**Comment by harlanj** [comment]
It always freezes up for me at this point below:

```
Meteor project detected...

WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

   Processing files with flemay:less-aut...  |
```

**Comment by fvpDev** [comment]
Will try now...typically when I use modulus-cli it takes ~10 min. And yeah, I have a lot of .less files & vars

**Comment by harlanj** [comment]
This is what i did:

```
$ npm uninstall -g modulus
$ npm install -g modulus@5
$ modulus deploy
```

I installed `v5` of the CLI to demeteorize locally

**Comment by fvpDev** [comment]
Ok, doing that now. Wait, so does it work after that or are you still wondering how long it takes for me locally?

**Comment by harlanj** [comment]
It finished deploying, but just took literally forever. About 10 minutes to `demeteorize` the app then it went through the deploy process.

**Comment by harlanj** [comment]
That process worked for me. So basically if your app is too big, your build will fail. That's what it's looking like so far.

**Comment by fvpDev** [comment]
Yeah...it's never taken more than 10 min...I correct my statement from earlier; it usually takes like 3-5 minutes to deploy.

**Comment by harlanj** [comment]
I'm deploying again with the `time` command just to see exactly how long the demeteorize step takes for your app.

**Comment by fvpDev** [comment]
Like `modulus deploy --time`?

**Comment by harlanj** [comment]
`time modulus deploy`

**Comment by fvpDev** [comment]
oh lol I'm using Win10

**Comment by harlanj** [comment]
Haha my bad! But it took about 3-5 mins as you noted before. I'm going to do one more clean deploy for your project just to confirm on time. But I am sure that your project may be too big for our build servers to build.

**Comment by fvpDev** [comment]
It's literally only ~3.6 MB...never ever had a problem before. 3.4 MB of that is the /public/img folder with all the images

**Comment by harlanj** [comment]
Give this a try as well:

1) Go to your project's "Home" page
2) Download the source
3) Deploy the source with the CLI@v5

Idk if you can do something like `echo $(time) && modulus deploy && echo $(time)` in Windows. But I say that just so you can see how long it takes. Mine is stuck at the less files again.

**Comment by fvpDev** [comment]
Why are you asking me to use v5 when it was working fine with v6.1.1? I'm so confused... Like I said before: yesterday from 14-18 hours ago I was deploying frequently (2-3 min in between deployments) with modulus-cli v6.1.1 and it was working absolutely phenomenally. This issue has nothing to do with how big my project is.

**Comment by fvpDev** [comment]
Also, I don't understand...you just said it took 3-5 minutes like I noted but now it's stuck again? lol

**Comment by harlanj** [comment]
If you repeat the process I noted above then you could confirm/deny that you're running into the same problem that I'm running into. Also you noted that you needed a workaround since this is your production app. So I was trying to get things back up and running without having to do custom things. Those are the reasons why I noted all these things. Lastly, from pulling your source, it took me 16 minutes to deploy.

```
[project-80631] time modulus deploy -p project-80631                                                                                                                       14:35:04
Welcome to Modulus
You are logged in as jeremiah
Selecting project-80631

Meteor project detected...

Changes to your project's package version selections:

wylio:mandrill  removed from your project


WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

Compressing project...
19.3 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Node.js runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /programs/server/package.json
Installing node 0.10.41
Installing npm 3.10.5
Installing packages from /programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.13 install /mnt/input/programs/server/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/mnt/input/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/mnt/input/programs/server/node_modules/fibers/build'
Installed in `/mnt/input/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
meteor-dev-bundle@0.0.0 /mnt/input/programs/server
├── amdefine@1.0.0
├── ansi-regex@0.2.1
├── ansi-styles@1.1.0
├── asap@2.0.4
├── escape-string-regexp@1.0.5
├── fibers@1.0.13
├── has-ansi@0.1.0
├── meteor-promise@0.7.2
├── promise@7.1.1
├── semver@4.1.0
├── source-map@0.1.32
├── source-map-support@0.3.2
├── strip-ansi@0.3.0
├── supports-color@0.2.0
├── type-of@2.0.1
└── underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
v0.10.41
deploy -> v0.10.41
Uploading completed build.
Provisioning and deploying bundle to servos...

[✓] project-80631 running at project80631-83053.onmodulus.net
modulus deploy -p project-80631  866.54s user 25.23s system 90% cpu 16:28.37 total
```

**Comment by fvpDev** [comment]
Ok, trying that..

**Comment by fvpDev** [comment]
@harlanj
Well...I recently deployed the most updated version of my project (using v6.1.1) and canceled it before it finished to try to do the thing with v5 but it seemed to have finished up anyway and the deployment is current with my local. There is a change that I made: I was having an .less loop that I halved in size between the deployment that you were testing with and the most recent one to see if that was what was causing the hang-up with `flemay:less-autoprefixer`. I think maybe the project, when uploading it, is 3.6MB but during compilation it blows up too be too big. I'll update the above previous comment once it's done running with v5 for you.

**Comment by fvpDev** [comment]
Lol No idea why it failed but here is my `ls`
![image](https://cloud.githubusercontent.com/assets/10249425/17070914/950b03ca-502c-11e6-8a32-81a5d22ef003.png)

**Comment by fvpDev** [comment]
What is the project size limit?

**Comment by fvpDev** [comment]
Any progress on this?

**Comment by jackboberg** [comment]
@fvpDev It does not look (to me) like you are hitting project size limits, since you are not seeing a `ENOSPC` error. I think the current build server limit is 4GB of space, but that can be deceiving since at times your files are duplicated between input/output.

**Comment by harlanj** [comment]
@fvpDev When downgrading the CLI to v5 you need to make sure it's a Node.js runtime. But let's disregard trying things on v5 of the CLI. But that's why your deploy failed using v5 of the CLI. 

When using v6 of the CLI, it seems like it sometimes passes. Unfortunately I cannot clearly identify why it's failing during build. In regards to size, @jackboberg said what I was going to say. There is an open issue on [`demeteorizer`](https://github.com/onmodulus/demeteorizer/issues/178) to change the Meteor output. This may help, but requires some work on `demeteorizer` first.

**Comment by jackboberg** [comment]
how about we remove deploying from the equation, and just test outputs using `meteor build` or `demeteorizer`. It does not seem like you are having issues uploading, so why not try recreating the situation on the build server locally:

```
docker pull onmodulus/build-meteor
docker run -it -e "INPUT_DIR=/mnt/in" -e "OUTPUT_DIR=/mnt/out" -v /tmp/out:/mnt/out -v $(pwd):/mnt/in onmodulus/build-meteor build
```

@fvpDev I know you are on windows, so this might be impossible. I don't have access to your source, so maybe @harlanj can try this and report back..

**Comment by fvpDev** [comment]
Okie dokie y'all. Meanwhile I'm redeveloping and cleaning up a lot of my code; it really does take too long to compile all the `.less` vars I have; I had a combination of my own UX + Semantic-UI (sUI) due to limitations sUI presented but since sUI has been upgraded to v2.2.x I'm probably going to ditch my UX.
Also...I never really migrated my code with Meteor 1.3 to use modules and such; idk the relevance to this current issue but maybe it'll help as well.

**Comment by fvpDev** [comment]
I ended up not having to ditch any code! Looks like this ended up being one of my problems:
https://github.com/meteor/meteor/issues/7206#issuecomment-230332826
(which includes instructions for migration to Meteor 1.3+)

I have a new issue, now though but I think I just need help because I don't know what to:
