### ISSUE TITLE
Meteor 1.4

### ISSUE THREAD

**Issue by flean** [onmodulus/modulus-cli#128]
Deploying to Meteor runtime environment with CLI I get this error

```
/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 1.4

    at new SemVer (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:566:10)
    at Function.gte (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:615:10)
    at Project.isSupported (/usr/local/lib/node_modules/modulus/lib/controllers/project.js:771:17)
    at /usr/local/lib/node_modules/modulus/lib/controllers/project.js:246:34
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by hassanasad** [comment]
Yeah same here  - i just upgraded Meteor to 1.4 and now stuck with modulus deployment issue :(

I just updated npm modulus package and still the same issue.

**Comment by jackboberg** [comment]
We need to convert Meteor's non-semver version string into something we can compare to our minimum supported `1.3`. We'll get a patch out as soon as possible.

**Comment by jackboberg** [comment]
The issue is [here](https://github.com/onmodulus/modulus-cli/blob/master/lib/controllers/project.js#L757-L772):

```
> semver.get('1.4', '1.3.0')
TypeError: semver.get is not a function
    at repl:1:8
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

need to pad out the right side so we can expect `x.x.x`
