### ISSUE TITLE
Meteor 1.4 and modulus incompatibility

### ISSUE THREAD

**Issue by hassanasad** [onmodulus/modulus-cli#136]
After upgrading to Meteor 1.4, modulus deployments are failing.

I am guessing it could be the node version mismatch? Meteor < 1.4 used Node versions like v0.10.41 - Meteor 1.4 uses Node version 4.4.7

There is no apparent error on the CLI:
```
$ modulus deploy
Welcome to Modulus
You are logged in as XYZ
[?] Are you sure you want to use project ABC? (yes) 
Deploying Meteor version 1.4

Compressing project...
1.4 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v0.10.41 (npm v3.9.6)
Initializing Meteor environment.
Using METEOR@1.4.
Demeteorizing application...
```

It stays on that last line for more than 5mins and then finally deploys. However on the modulus when i check logs its lots and lots of errors such as:
```
Now using node v0.10.41 (npm v3.9.6)
Found package.json: ./bundle/programs/server/package.json
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/bundle/programs/server
> node ../../main


assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/mnt/app/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.41/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/bundle/programs/server/npm-debug.log
Now using node v0.10.41 (npm v3.9.6)
Found package.json: ./bundle/programs/server/package.json
```

Perhaps Modulus needs to upgrade their Node version for Meteor 1.4 deployments to 4.4.7

**Comment by jackboberg** [comment]
@hassanasad Thanks for the report. Since this is not an issue with the Modulus CLI, I opened a [new issue](https://github.com/onmodulus/docker-build-meteor/issues/25) on our build image.
