### ISSUE TITLE
JS project wont deploy - has no method 'assign' (uploader.js)

### ISSUE THREAD

**Issue by timmyg** [onmodulus/modulus-cli#142]
Getting the following error deploying a meteor 1.3.4.1 project (as well as a nodejs/express project). Both issues started happening this morning (a few hours ago).

```
Uploading project...
e/rof/.nvm/v0.10.46/lib/node_modules/modulus/lib/controllers/uploader.js:73
qs: Object.assign({ authToken: apiKey }, options),
^
TypeError: Object function Object() { [native code] } has no method 'assign'
at /home/rof/.nvm/v0.10.46/lib/node_modules/modulus/lib/controllers/uploader.js:73:18
at Object.oncomplete (fs.js:108:15)
```

installed modulus via...
```
npm install -g modulus
-npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
\e/rof/.nvm/v0.10.46/bin/modulus -> /home/rof/.nvm/v0.10.46/lib/node_modules/modulus/bin/modulus
modulus@6.3.0 /home/rof/.nvm/v0.10.46/lib/node_modules/modulus
opener@1.3.0
progress@0.1.0
through@2.3.4
split@0.3.0
colors@0.6.2
find-file-sync@0.0.2
text-table@0.2.0
semver@5.3.0
node-uuid@1.3.3
async@0.1.22
commander-plus@0.0.6 (keypress@0.1.0)
underscore@1.4.4
fstream-ignore@1.0.5 (inherits@2.0.1, minimatch@3.0.3, fstream@1.0.10)
update-notifier@1.0.2 (is-npm@1.0.0, semver-diff@2.1.0, lazy-req@1.1.0, xdg-basedir@2.0.0, chalk@1.1.3, boxen@0.6.0, configstore@2.0.0, latest-version@2.0.0)
prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, utile@0.2.1, winston@0.8.3)
fs-tools@0.2.11 (async@0.2.10, lodash@2.4.2)
request@2.27.0 (aws-sign@0.3.0, forever-agent@0.5.2, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, cookie-jar@0.3.0, json-stringify-safe@5.0.1, mime@1.2.11, node-uuid@1.4.7, form-data@0.1.4, http-signature@0.10.1, hawk@1.0.0)
zip-stream@0.5.1 (compress-commons@0.2.9, readable-stream@1.0.34, lodash@3.2.0)
```

**Comment by jackboberg** [comment]
This recent addition should be rewritten to support node `v0.10.x` (for now). That should be in a major release, that is well documented...

In the meantime, you could install `v4.x` to get around this issue. Your project doesn't need to be update, just your shell when running `modulus deploy`.

**Comment by jackboberg** [comment]
You can install the hot fix from github, until I get this released as `v6.3.1`:

`npm i onmodulus/modulus-cli#hotfix/support-node-0.10 -g`

**Comment by danielparas** [comment]
thanks @jackboberg - had similar issue and hotfix solved deploy script but meteor server then fails to boot up. File a sperate issue with modulus support for this.

Also, not sure if it's related but `modulus status` command in terminal gives the following error:

```
TypeError: Cannot call method 'forEach' of undefined
    at Request._callback (/usr/local/lib/node_modules/modulus/lib/commands/status.js:41:21)
    at Request.self.callback (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by jackboberg** [comment]
@danielparas It looks like your error is already handled with recent fixes. Try:

`modulus deploy --node-version 4`

**Comment by jackboberg** [comment]
```
› npm dist-tag ls modulus
latest: 6.3.1
```

**Comment by danielparas** [comment]
thanks @jackboberg - everything in order now :)

**Comment by timmyg** [comment]
@jackboberg yep - looks good. Thanks!
