### ISSUE TITLE
Modulus Status error on staging

### ISSUE THREAD

**Issue by chosenken** [onmodulus/modulus-cli#146]
I get the following error when I run `modulus status` while logged into staging:

```
Welcome to Modulus
You are logged in as staging-ops
/usr/local/lib/node_modules/modulus/lib/commands/status.js:41
    body.components.forEach(function (component) {
                   ^

TypeError: Cannot read property 'forEach' of undefined
    at Request._callback (/usr/local/lib/node_modules/modulus/lib/commands/status.js:41:20)
    at Request.self.callback (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:129:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:873:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/request/request.js:824:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by jackboberg** [comment]
onmodulus/modulus-cli#144
