### ISSUE TITLE
TypeError when running any `modulus project *` command with version 3.7.1

### ISSUE THREAD

**Issue by andrewtamura** [onmodulus/modulus-cli#49]
After updating to modulus 3.7.1 I get a TypeError when running modulus project commands. Login appears to work fine. 

```
/usr/local/lib/node_modules/modulus/lib/commands/project.js:993
        projects[i].images.run ?
                          ^
TypeError: Cannot read property 'run' of undefined
    at Object.project.chooseProjectPrompt (/usr/local/lib/node_modules/modulus/lib/commands/project.js:993:27)
    at /usr/local/lib/node_modules/modulus/lib/commands/project.js:669:15
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/modulus/lib/librarian/http.js:134:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

**Comment by fiveisprime** [comment]
Update to modulus@3.7.2 and see if you have the same issue.

**Comment by andrewtamura** [comment]
Thanks, 3.7.2 does not have this problem.

**Comment by fiveisprime** [comment]
:+1:
