### ISSUE TITLE
modulus login results in "TypeError: Cannot read property 'api_uri' of undefined"

### ISSUE THREAD

**Issue by markstos** [onmodulus/modulus-cli#7]
I just downloaded the latest modulus code from Github, and when I ran
"modulus login", I get an error that:

```
TypeError: Cannot read property 'api_uri' of undefined
```

Here's full stack returned:

```
$ modulus login

/usr/lib/node_modules/modulus/lib/common/api.js:8
if (typeof userConfig.data.api_uri !== 'undefined') {
                          ^
TypeError: Cannot read property 'api_uri' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/modulus/lib/common/api.js:8:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/modulus/lib/modulus.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

It's not clear what I'm supposed to do from here to continue logging in.

**Comment by shakeelmogify** [comment]
Please help me out, i am getting following error if i try to login in modulus.

TypeError: Cannot read property 'user' of undefined
    at module.exports.server.get.res.render.meta.title (/opt/modulus/aperture/build/server/lib/routes.js:5308:18)
    at callbacks (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:161:37)
    at param (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:135:11)
    at pass (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:142:5)
    at nextRoute (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:164:11)
    at module.exports.checkRedis (/opt/modulus/aperture/build/server/lib/routes.js:5228:5)
    at callbacks (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:161:37)
    at param (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:135:11)
    at pass (/opt/modulus/aperture/build/server/node_modules/express/lib/router/index.js:142:5)

**Comment by fiveisprime** [comment]
Sorry about that, the API server was having issues that caused this. It's all fixed up now.

**Comment by shakeelmogify** [comment]
Thanks @fiveisprime for quick response. It's working now.
